name: base
channels:
  - rdkit
  - defaults
dependencies:
  - rdkit
  - pip:
    - scipy
    - matplotlib
    - psutil
    - pandas
    - pathos
    - seaborn
    - numpy
    - setuptools
    - pywindowx
    - numpydoc
